%% 
% Riccardo Antonello (riccardo.antonello@unipd.it)
%
% July 23, 2025
%
% Dept. of Information Engineering, University of Padova
%
clear;
clc;
close all force;

%% Serial datalogger
% %   interactive data-logging
% serial_datalog( 'COM3', ...
%     packetSpec, ...
%     'baudrate', 115200, ...
%     'txsampletime', 0.01, ...
%     'buffersize', 100000, ...
%     'plotrefreshratio', 10, ...
%     'plotwidth', 5);

% % wireless data log
% data = udp_datalog('192.168.4.1',9090, packetSpec, 'buffersize', 1000000);

%%
% Riccardo Antonello (riccardo.antonello@unipd.it)
%
% December 05, 2025
%
% Dept. of Information Engineering, University of Padova
%

%   start UDP datalogger with specified input arguments
localUdpPort = 9090;
remoteUdpPort = 12345;
remoteIpAddress = "192.168.4.1";
baudRate = 115200;
packetSpec = {'2*single', '2*single'};

plotsGridSize = [2, 1];
plotsContentList = [ ...
    1, 1, 1; ...
    2, 2, 1];

udpDataLoggerApp( ...
    "LocalUdpPort", localUdpPort, ...
    "RemoteUdpPort", remoteUdpPort, ...
    "RemoteIpAddress", remoteIpAddress, ...
    "PacketSpec", packetSpec, ...
    "enableStartStopCmds", false, ...
    "txStartCmd", 65, ...
    "txStopCmd", 66, ...
    "enableCOBS", true, ...
    "enableNullTerminator", false, ...
    "bufferSize", 2000, ...
    "txSampleTime", 0.01, ...
    "enableLogToWorkspace", true, ...
    "enableSaveOnExit", true, ...
    "varName", "data", ...
    "plotsGridSize", plotsGridSize, ...
    "plotsContentList", plotsContentList, ...
    "plotsDuration", 5, ...
    "plotsRefreshRatio", 8);


