%%
% Riccardo Antonello (riccardo.antonello@unipd.it)
%
% December 05, 2025
%
% Dept. of Information Engineering, University of Padova
%

close all force; clc;

%   start UDP datalogger with specified input arguments
localUdpPort = 9090;
remoteUdpPort = 9090;
remoteIpAddress = "192.168.4.1";
packetSpec = {'2*single', '2*single'};
baudRate = 115200;

plotsGridSize = [2, 1];
plotsContentList = [ ...
    1, 1, 1; ...
    2, 2, 1];

udpDataLoggerApp( ...
    "LocalUdpPort", localUdpPort, ...
    "RemoteUdpPort", remoteUdpPort, ...
    "RemoteIpAddress", remoteIpAddress, ...
    "PacketSpec", packetSpec, ...
    "enableStartStopCmds", false, ...
    "txStartCmd", 65, ...
    "txStopCmd", 66, ...
    "enableCOBS", true, ...
    "enableNullTerminator", true, ...
    "bufferSize", 2000, ...
    "txSampleTime", 0.01, ...
    "enableLogToWorkspace", true, ...
    "enableSaveOnExit", true, ...
    "varName", "data", ...
    "plotsGridSize", plotsGridSize, ...
    "plotsContentList", plotsContentList, ...
    "plotsDuration", 5, ...
    "plotsRefreshRatio", 8);

