%% 
% Riccardo Antonello (riccardo.antonello@unipd.it)
%
% July 23, 2025
%
% Dept. of Information Engineering, University of Padova
%
clear;
%   packet specifier
packetSpec = {'2*single', '2*single'};

%   interactive data-logging
serial_datalog( 'COM3', ...
    packetSpec, ...
    'baudrate', 115200, ...
    'txsampletime', 0.01, ...
    'buffersize', 100000, ...
    'plotrefreshratio', 10, ...
    'plotwidth', 5);
